### ISSUE TITLE
Any planning for route based caching ???

### ISSUE THREAD

**Issue by roninaruka** [denbon05/fastify-lcache#51]

**Comment by denbon05** [comment]
@roninaruka thank you for the suggestion! Route-based caching could be a valuable addition.
For now, only [route excluding is implemented](https://github.com/denbon05/fastify-lcache?tab=readme-ov-file#api)
```ts
app.register(lcache, { excludeRoutes: [...] });
```
we’re open to considering it.
If you're interested, we'd welcome a contribution for route-based caching! We can provide guidance on implementation if needed. We'll leave this issue open for now to gather more feedback. We'll explore possible implementations in future versions.

**Comment by denbon05** [comment]
Route caching introduced in [v2.2.0](https://github.com/denbon05/fastify-lcache/releases/tag/v2.2.0)

Priority of `excludeRoutes`:
- If a route matches any pattern in `excludeRoutes`, it will never be cached.
- This priority ensures that specified routes in `excludeRoutes` are always ignored by the cache, regardless of any `includeRoutes` setting.

Default Inclusion with `includeRoutes`: '*':
- When `includeRoutes` is set to '*' (the default), all routes are included for caching, except those listed in `excludeRoutes`. 
- This allows users to set general caching behavior but exclude specific routes as needed.

Explicit Inclusion and Exclusion:
- If specific routes are defined in `includeRoutes` (e.g., ['/api/users', '/api/orders']), only those routes are eligible for caching.
- In this case, `excludeRoutes` still takes priority, meaning any route listed in `excludeRoutes` will be ignored even if specified in `includeRoutes`.

Unspecified Routes:
- When `includeRoutes` specifies particular routes, **only those specified are cached**, while all other routes (not in either list) are ignored by the cache.
